config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
    confirmations: 'users/confirmations'}, path_names: { sign_in: 'login', sign_out: 'logout'}
  
  authenticated :user do
    resources :users, only: [:index, :update, :edit] do
      member do 
        get 'profile'
      end
      collection do 
        patch 'update_password'
      end
      resources :addresses
    end
    
    resources :contacts do
      collection do
        get 'search'
      end
      resources :addresses
    end
    resources :fund_transfers
    
  end
  root to: 'admins#index'
  
  
  resources :admins, only: [:index]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/fund_transfer.rb
class FundTransfer < ApplicationRecord
  belongs_to  :user
  #belongs_to  :contact
  default_scope { order('transaction_date desc') }
  
  self.per_page = 10
  
  AssetType = [
    ['CREDIT', 'cr'],
    ['DEBIT', 'dr'],
    ['DEPOSIT', 'dp'],
    ['LOAN', 'ln']
  ]
  
  #before_create :assign_transaction_number
  
  def assign_transaction_number
    self.transaction_number = self.class.get_transaction_number
    self.transaction_date = Date.today
  end
  
  def self.get_transaction_number
    ft_no = SecureRandom.hex(5)       
    while where(transaction_number: ft_no).present?
      ft_no = SecureRandom.hex(5)
    end
    ft_no
  end
  
  def ist_time_format
    transaction_date.strftime('%a %d %b %Y')
  end
  
  def credit_amount
    asset_type == 'cr' ? sprintf('%.2f', amount) : sprintf('%.2f', 0)
  end
  
  def debit_amount
    asset_type == 'dr' ? sprintf('%.2f', amount) : deposit_amount
  end
  
  def loan_amount
    asset_type == 'ln' ? sprintf('%.2f', amount) : sprintf('%.2f', 0)
  end
  
  def deposit_amount
    asset_type == 'dp' ? sprintf('%.2f', amount) : sprintf('%.2f', 0)
  end
  
  def transfer_to
    contact_id.blank? ? to_other : contact.name 
  end
  
  def contact
    Contact.find(contact_id)
  end

  def self.add_decimal_prefix(amount, num_of_zeros=2)
    sprintf("%.#{num_of_zeros}f", amount)
  end
end

app/controllers/fund_transfers_controller.rb
class FundTransfersController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @fts = current_user.fund_transfers.paginate(:page => params[:page])    
    @tot_cr, @tot_dr, @tot_dp, @tot_ln = current_user.monthly_transactions    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fts }
    end
  end
  
  def new
    @ft = FundTransfer.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ft }
    end
  end
  
  def create
    @ft = current_user.fund_transfers.build(fund_transfer_params)
    respond_to do |format|
      if @ft.save
        format.html { redirect_to @ft, notice: 'Trasfer was successfully made.' }
        format.json { render json: @ft, status: :created, location: @ft }
      else
        puts @ft.errors.messages
        format.html { render action: "new" }
        format.json { render json: @ft.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @ft = current_user.fund_transfers.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ft }
    end
  end
  
  def edit
    @ft = current_user.fund_transfers.find(params[:id])
  end
  
  def update
    @ft = current_user.fund_transfers.find(params[:id])
    respond_to do |format|
      if @ft.update_attributes(fund_transfer_params)
        format.html { redirect_to @ft, notice: 'Fund transfer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ft.errors, status: :unprocessable_entity }
      end
    end
  end
  
  
  def destroy
    @ft = current_user.fund_transfers.find(params[:id])
    @ft.destroy
    respond_to do |format|
      format.html { redirect_to fund_transfers_path, notice: 'Fund was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  
  private
  def fund_transfer_params
    params.require(:fund_transfer).permit(:contact_id, :to_other, :asset_type, :amount, :transaction_number, :transaction_date)
  end
  
  
end

app/helpers/fund_transfers_helper.rb
module FundTransfersHelper
  def dd_mm_yy(date, format='dd-mm-yyyy')
    case format
    when 'dd-mm-yyyy'
      date.strftime('%d-%m-%Y')
    end
    
  end
end

app/views/fund_transfers/_form.html.erb
<style type="text/css">
  label .error{
    color:#ff0000;
  }
</style>
<%= form_for @ft, html: {class: "form-horizontal", id: 'fund_transfer_form' } do |f| %>
    <div class="form-group">
      <label class="col-sm-2 control-label">Name</label>
      <div class="col-sm-3">
        <%= f.select :contact_id, Contact.all.collect { |p| [ p.name, p.id ] }, {prompt: 'Select From Contact', selected: params[:contact_id] || @ft.contact_id}, {class: "form-control"}    %>
        </div>        
        <div class="col-sm-3">
          <%= f.text_field :to_other, class: "form-control", placeholder: 'Enter Other Name'    %>
          </div>

        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Amount</label>
          <div class="col-sm-3">
            <%= f.text_field :amount, class: "form-control"    %>
            </div>
            <label class="col-sm-1 control-label">In / Out</label>
            <div class="col-sm-2">
              <%= f.select :asset_type, FundTransfer::AssetType, {}, {class: "form-control"} %>
              </div>
            </div>


            <div class="form-group">
              <label class="col-sm-2 control-label">Transaction Date</label>
              <div class="col-sm-3 input-group date">
                <%#= @ft.transaction_date.strftime('%d-%m-%Y') %>
                <%= f.text_field :transaction_date, class: "form-control" , value: @ft.transaction_date ? dd_mm_yy(@ft.transaction_date) : dd_mm_yy(Date.today) %> 
                  <span class="input-group-addon">
                    <span class="fa fa-calendar">
                    </span>
                  </span>
                </div>
                <label class="col-sm-1 control-label">Number</label>
                <div class="col-sm-2">
                  <%= f.text_field :transaction_number, class: "form-control" %>
                  </div>
                </div>


                <div class="form-group">
                  <label class="col-sm-2 control-label"></label>
                  <div class="col-sm-6">
                    <%= f.submit class: 'btn btn-primary' %>
                    </div>
                  </div>
                <%end%>


                <script type="text/javascript">
                  $(document).ready(function() {
                    $("#fund_transfer_form").validate({
                      rules: {
                        'fund_transfer[contact_id]': {
                          required: {
                            depends: function(element) {
                              return $("#fund_transfer_to_other").val() === '';
                            }
                          }
                        },
                        'fund_transfer[to_other]': {
                          required: {
                            depends: function(element) {
                              return $("#fund_transfer_contact_id").val() === '';
                            }
                          }
                        }, 
                        'fund_transfer[amount]': {
                          required: true
                        },
                        'fund_transfer[asset_type]': {
                          required: true
                        },                        
                        'fund_transfer[transaction_time]': {
                          required: true
                        },                        
                        'fund_transfer[transaction_number]': {
                          //required: true
                        }
                        
                      }
                    });
                    $('.date').datetimepicker({
                      format: 'DD-MM-YYYY'
                    });
                  });






                </script>
                </script>

app/views/fund_transfers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <i class="fa fa-arrow-left" onclick="goBack();" style="cursor:pointer;"></i>
        Edit Fund
      </header>
      <div class="panel-body">
        <%= render partial: 'form' %>
      </div>
    </section>
  </div>
</div>

app/views/fund_transfers/index.html.erb
<style type="text/css">
  .control-label{
    //text-align:right;
    padding:8px 0px;
    margin-left:8px;
  }
</style>

<div class="row">
  <div class="col-lg-9">    
    <h4 class="page-header"><i class="fa fa-money"></i> Fund Transfer Dashboard</h4>    
  </div>
  <div class="col-lg-3 digg_pagination" style="padding:0;background:#eeeeee;">            
    <%= will_paginate @fts, :container => false %>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <div class="col-sm-2 control-label" style="">Monthly Credit : &nbsp;&nbsp;
        <i class="fa fa-inr" aria-hidden="true"></i><b><%= FundTransfer.add_decimal_prefix(@tot_cr.try(:total_amount).to_f) %></b>
      </div>
      <div class="col-sm-2 control-label" style="margin-left:4%;">Debit : &nbsp;&nbsp;
        <i class="fa fa-inr" aria-hidden="true"></i><b><%= FundTransfer.add_decimal_prefix(@tot_dr.try(:total_amount).to_f) %></b>
      </div>

      <div class="col-sm-2 control-label">Deposit : &nbsp;&nbsp;
        <i class="fa fa-inr" aria-hidden="true"></i><b><%= FundTransfer.add_decimal_prefix(@tot_dp.try(:total_amount).to_f) %></b>
      </div>

      <div class="col-sm-2 control-label">Loan : &nbsp;&nbsp;
        <i class="fa fa-inr" aria-hidden="true"></i><b><%= FundTransfer.add_decimal_prefix(@tot_ln.try(:total_amount).to_f) %></b>
      </div>

      <div class="col-sm-2 control-label">Balance : &nbsp;&nbsp;
        <i class="fa fa-inr" aria-hidden="true"></i><b><%= FundTransfer.add_decimal_prefix(@tot_cr.try(:total_amount).to_f - @tot_dr.try(:total_amount).to_f - @tot_dp.try(:total_amount).to_f) %></b>
      </div>

      <div style="float:right;margin-right:1%;padding:8px 0px;">         
        <a class="" href="<%= new_fund_transfer_path %>"><i class="fa fa-plus-circle"></i> New Fund</a>
      </div>

      <table class="table table-striped table-advance table-hover">
        <tbody>
          <tr>
            <th><i class="fa fa-user"></i> Name</th>
            <th><i class="fa fa-clock-o"></i> Transaction Date</th>
            <th><i class=""></i> Transaction Number</th>
            <th><i class="fa fa-arrow-down "></i> Credit</th>
            <th><i class="fa fa-arrow-up "></i> Debit</th>
            <th>Loan</th>
            <th><i class="icon_cogs"></i> Action</th>
          </tr>

          <%@fts.each do |ft|%>
            <tr>
              <td><%= ft.transfer_to %></td>
              <td><%= ft.ist_time_format %></td>
              <td><%= ft.transaction_number %></td>
              <td><%= ft.credit_amount %></td>
              <td><%= ft.debit_amount %></td>
              <td><%= ft.loan_amount %></td>
              <td>
                <div class="btn-group">
                  <a class="btn btn-info" href="<%= fund_transfer_path(ft) %>" title="Show Transfer"><i class="fa fa-eye"></i></a>
                  <a class="btn btn-success" href="<%= edit_fund_transfer_path(ft) %>" title="Edit Transfer"><i class="fa fa-edit"></i></a>
                  <a class="btn btn-danger" href="<%= fund_transfer_path(ft)%>" data-method="DELETE" data-confirm="Are you sure?" title="Delete Transfer"><i class="fa fa-trash-o"></i></a>
                </div>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table> 
      <div class="col-lg-3 digg_pagination" style="padding-top:10px;background:#eeeeee;float:right">            
        <%= will_paginate @fts, :container => false %>
      </div>
    </section>    
  </div>
</div>

app/views/fund_transfers/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <i class="fa fa-arrow-left" onclick="goBack();" style="cursor:pointer;"></i>
        Add New Fund
      </header>
      <div class="panel-body">
        <%= render partial: 'form' %>
      </div>
    </section>
  </div>
</div>

app/views/fund_transfers/show.html.erb
<style type="text/css">
  .control-label{
    padding-top:0 !important;
  }
</style>

<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <i class="fa fa-arrow-left" onclick="goBack();" style="cursor:pointer;"></i>
        Fund Transfer Detail
      </header>

      <div class="panel-body">
        <div class="form-horizontal" style="width:100%;">            
          <div class="form-group">
            <label class="col-sm-2 control-label">Name</label>
            <div class="col-sm-6 ">
              <%= @ft.transfer_to %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Transaction Date</label>
            <div class="col-sm-6 ">
              <%= @ft.ist_time_format %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Transaction Number</label>
            <div class="col-sm-6 ">
              <%= @ft.transaction_number %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Asset Type</label>
            <div class="col-sm-6 ">
              <%= FundTransfer::AssetType.detect{|u| u[1] == @ft.asset_type }.first  %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Amount</label>
            <div class="col-sm-6 ">
              <%= sprintf('%.2f', @ft.amount) %>
            </div>
          </div>


        </div>
      </div>
    </section>
  </div>
</div>