config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
    confirmations: 'users/confirmations'}, path_names: { sign_in: 'login', sign_out: 'logout'}
  
  authenticated :user do
    resources :users, only: [:index, :update, :edit] do
      member do 
        get 'profile'
      end
      collection do 
        patch 'update_password'
      end
      resources :addresses
    end
    
    resources :contacts do
      collection do
        get 'search'
      end
      resources :addresses
    end
    resources :fund_transfers
    
  end
  root to: 'admins#index'
  
  
  resources :admins, only: [:index]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :confirmable
       
  has_many :contacts,  dependent: :destroy
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :fund_transfers,  dependent: :destroy
  
  def monthly_transactions(start_date=Date.today)
    start_month = start_date.at_beginning_of_month
    end_month = start_date.end_of_month
    fts = fund_transfers.select('sum(amount) as total_amount, asset_type').where(transaction_date: start_month..end_month).group('asset_type')
    cr = fts.select{|ft| ft.asset_type == 'cr'}.first
    dr = fts.select{|ft| ft.asset_type == 'dr'}.first
    dp = fts.select{|ft| ft.asset_type == 'dp'}.first
    ln = fts.select{|ft| ft.asset_type == 'ln'}.first
    return cr,dr,dp,ln
  end
  
  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    new_user_session_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController  
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :get_user
  def profile
    @address = @user.addresses.first
  end
  
  def update
    respond_to do |format|
      if @user.update_attributes(user_params)        
        format.html { redirect_to profile_user_path(@user), notice: 'User was successfully updated.' }        
        format.json { head :no_content }
      else
        @address = @user.addresses.first
        format.html { render action: "profile" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update_password
    if @user.update(user_params)
      # Sign in the user by passing validation in case their password changed
      bypass_sign_in(@user)
      redirect_to root_path
    else
      render "edit"
    end
  end  
  
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <i class="fa fa-arrow-left" onclick="goBack();" style="cursor:pointer;"></i>
        Update Password
      </header>

      <div class="panel-body">
        <%= form_for @user, html: {class: "form-horizontal", id: 'update_password_form' } do |f| %>
            <div class="form-group">
              <label class="col-sm-2 control-label">Password</label>
              <div class="col-sm-5">
                <%= f.password_field :password, class: "form-control", autocomplete: "off" %>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label">Confirm Password</label>
                <div class="col-sm-5">
                  <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "off" %>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-sm-2 control-label"></label>
                  <div class="col-sm-6">
                    <%= f.submit class: 'btn btn-primary' %>
                    </div>
                  </div>

                <%end%>
              </div>
            </section>
          </div>
        </div>

app/views/users/profile.html.erb
<style type="text/css">
  .control-label{
    padding-top:0 !important;
  }
  .form-group{
    border-bottom: none !important;
  }

  .text-left{
    text-align:left !important;
  }
</style>

<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <i class="fa fa-arrow-left" onclick="goBack();" style="cursor:pointer;"></i>
        User Detail
        <div style="float:right;margin-right:1%;padding:0px 0px;">          
          <% if @address.present? %>
            <a class="" href="<%= edit_user_address_path(@user, @address) %>"><i class="fa fa-plus-circle"></i> Edit Address</a>
          <%else%>
            <a class="" href="<%= new_user_address_path(@user) %>"><i class="fa fa-plus-circle"></i> Add Address</a>
          <%end%>
        </div>
      </header>


      <div class="panel-body">
        <div class="form-horizontal col-lg-6" style="">            
          <div class="form-group">
            <label class="col-sm-2 control-label">Email</label>
            <div class="col-sm-6 control-label text-left">
              <%= @user.email %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Name</label>
            <div class="col-sm-6 control-label text-left">
              <%= @user.full_name %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Address</label>
            <div class="col-sm-8 control-label text-left">
              <%= @address.full_address %>
            </div>
          </div>
        </div>


        <%= form_for @user, html: {class: "form-horizontal col-lg-6", id: 'profile_form' } do |f| %>
            <div class="form-group">
              <label class="col-sm-3 control-label">First Name</label>
              <div class="col-sm-6">
                <%= f.text_field :first_name, class: "form-control"    %>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-3 control-label">Last Name</label>
                <div class="col-sm-6">
                  <%= f.text_field :last_name, class: "form-control"    %>
                  </div>
                </div>






                <div class="form-group">
                  <label class="col-sm-3 control-label"></label>
                  <div class="col-sm-6">
                    <%= f.submit 'Update', class: 'btn btn-primary' %>
                    </div>
                  </div>

                <%end%>


              </div>
      
      <hr>
            </section>
          </div>
        </div>