config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
    confirmations: 'users/confirmations'}, path_names: { sign_in: 'login', sign_out: 'logout'}
  
  authenticated :user do
    resources :users, only: [:index, :update, :edit] do
      member do 
        get 'profile'
      end
      collection do 
        patch 'update_password'
      end
      resources :addresses
    end
    
    resources :contacts do
      collection do
        get 'search'
      end
      resources :addresses
    end
    resources :fund_transfers
    
  end
  root to: 'admins#index'
  
  
  resources :admins, only: [:index]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  has_many :addresses, as: :addressable, dependent: :destroy
  #has_many :fund_transfers,  dependent: :destroy
  
  default_scope { order('name asc') }
  self.per_page = 10
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController  
  def index
    @contacts = current_user.contacts.paginate(:page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cotacts }
    end
  end
  
  def new
    @contact = Contact.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end
  
  def create
    @contact = current_user.contacts.build(contact_params)
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    @contact = current_user.contacts.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end
  
  def edit
    @contact = current_user.contacts.find(params[:id])
  end
  
  def update
    @contact = current_user.contacts.find(params[:id])

    respond_to do |format|
      if @contact.update_attributes(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @contact = current_user.contacts.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  def search
    serchd_data = Contact.where("name like ?", "%#{params[:q].downcase}%")
		render json: serchd_data.as_json(only: [:name, :id])
  end
  
  
  private
  def contact_params
    params.require(:contact).permit(:user_id, :name, :email, :mobile_number_1, :mobile_number_2, :mobile_number_3)
  end
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<style type="text/css">
  label .error{
    color:#ff0000;
  }
</style>
<%= form_for @contact, html: {class: "form-horizontal", id: 'contact_form' } do |f| %>
    <div class="form-group">
      <label class="col-sm-2 control-label">Name</label>
      <div class="col-sm-6">
        <%= f.text_field :name, class: "form-control"    %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label">Email</label>
        <div class="col-sm-6">
          <%= f.email_field :email, class: "form-control"    %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 control-label">Mobile Number 1</label>
          <div class="col-sm-6">
            <%= f.text_field :mobile_number_1, maxlength: 10, class: "form-control"    %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Mobile Number 2</label>
            <div class="col-sm-6">
              <%= f.text_field :mobile_number_2, maxlength: 10, class: "form-control"    %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-sm-2 control-label">Mobile Number 3</label>
              <div class="col-sm-6">
                <%= f.text_field :mobile_number_3,maxlength: 10, class: "form-control"    %>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label"></label>
                <div class="col-sm-6">
                  <%= f.submit class: 'btn btn-primary' %>
                  </div>
                </div>

              <%end%>


              <script type="text/javascript">
                $(document).ready(function() {
                  $("#contact_form").validate({
                    rules: {
                      'contact[name]': {
                        required: true
                      },
                      'contact[email]': {
                        //required: true,
                        email: true
                      },
                      'contact[mobile_number_1]': {
                        required: true,
                        number: true,
                        minlength: 10,
                        maxlength: 10
                      }
                    },
                    'contact[mobile_number_2]': {
                      number: true,
                      minlength: 10,
                      maxlength: 10
                    },
                    'contact[mobile_number_3]': {
                      number: true,
                      minlength: 10,
                      maxlength: 10

                    },
                    messages: {
                      'contact[email]'
                              : "Please enter a valid email address."
                    }
                  });
                });
              </script>

app/views/contacts/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <i class="fa fa-arrow-left" onclick="goBack();" style="cursor:pointer;"></i>
        Edit Contact
      </header>
      <div class="panel-body">
        <%= render partial: 'form' %>
      </div>
    </section>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h4 class="page-header"><i class="fa fa-file"></i> Contact Dashboard</h4>    
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <div style="float:right;margin-right:1%;padding:8px 0px;">         
        <a class="" href="/contacts/new"><i class="fa fa-plus-circle"></i> New Contact</a>
      </div>

      <table class="table table-striped table-advance table-hover">
        <tbody>
          <tr>
            <th><i class="icon_profile"></i> Name</th>
            <th><i class="icon_mail_alt"></i> Email</th>                
            <th><i class="icon_mobile"></i> Mobile 1</th>
            <th><i class="icon_mobile"></i> Mobile 2</th>
            <th><i class="icon_mobile"></i> Mobile 3</th>
            <th><i class="icon_cogs"></i> Action</th>
          </tr>

          <%@contacts.each do |contact|%>
            <tr>
              <td><%= contact.name %></td>
              <td><%= contact.email %></td>                
              <td><%= contact.mobile_number_1 %></td>
              <td><%= contact.mobile_number_2 %></td>
              <td><%= contact.mobile_number_3 %></td>
              <td>
                <div class="btn-group">
                  <a class="btn btn-info" href="<%= contact_path(contact) %>" title="Show Contact"><i class="fa fa-eye"></i></a>
                  <a class="btn btn-success" href="<%= edit_contact_path(contact) %>" title="Edit Contact"><i class="fa fa-edit"></i></a>
                  <a class="btn btn-info" href="<%= new_contact_address_path(contact) %>" title="Add Address"><i class="icon_contacts_alt"></i></a>
                  <a class="btn btn-success" href="<%= new_fund_transfer_path(contact_id: contact.id) %>" title="Add Fund"><i class="fa fa-money"></i></a>
                  <a class="btn btn-danger" href="<%= contact_path(contact)%>" data-method="DELETE" data-confirm="Are you sure?" title="Delete Contact"><i class="fa fa-trash-o"></i></a>
                </div>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
      <div class="digg_pagination">            
        <%= will_paginate @posts, :container => false %>
      </div>
    </section>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <i class="fa fa-arrow-left" onclick="goBack();" style="cursor:pointer;"></i>
        New Contact
      </header>
      <div class="panel-body">
        <%= render partial: 'form' %>
      </div>
    </section>
  </div>
</div>

app/views/contacts/show.html.erb
<style type="text/css">
  .control-label{
    padding-top:0 !important;
  }
</style>
<div class="row">
  <div class="col-lg-12">
    <section class="panel">
      <header class="panel-heading">
        <i class="fa fa-arrow-left" onclick="goBack();" style="cursor:pointer;"></i>
        Contact Detail
      </header>

      <div class="panel-body">
        <div class="form-horizontal" style="width:100%;">            
          <div class="form-group">
            <label class="col-sm-2 control-label">Name</label>
            <div class="col-sm-6 ">
              <%= @contact.name %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Email</label>
            <div class="col-sm-6 ">
              <%= @contact.email %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Mobile Number 1</label>
            <div class="col-sm-6 ">
              <%= @contact.mobile_number_1 %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Mobile Number 2</label>
            <div class="col-sm-6 ">
              <%= @contact.mobile_number_2 %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-2 control-label">Mobile Number 3</label>
            <div class="col-sm-6 ">
              <%= @contact.mobile_number_3 %>
            </div>
          </div>

          <% @contact.addresses.each_with_index do |address, index| %>
            <div class="form-group">
              <label class="col-sm-2 control-label">Address <%= index + 1 %></label>
              <div class="col-sm-8">
                <%= address.full_address %>
                <a class="" href="<%= contact_address_path(@contact, address) %>" title="Show Address" style="margin-left:10px;"><i class="fa fa-eye"></i></a>
                <a class="" href="<%= edit_contact_address_path(@contact, address) %>" title="Edit Address" style="margin-left:10px;"><i class="fa fa-edit"></i></a>
                <a class="" href="<%= contact_address_path(@contact, address)%>" data-method="DELETE" data-confirm="Are you sure?" title="Delete Address" style="margin-left:10px;"><i class="fa fa-trash-o"></i></a>
              </div>                  
            </div>
          <%end if @contact.addresses.present?%>
        </div>
      </div>
    </section>
  </div>
</div>