config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations',
    confirmations: 'users/confirmations'}, path_names: { sign_in: 'login', sign_out: 'logout'}
  
  authenticated :user do
    resources :users, only: [:index, :update, :edit] do
      member do 
        get 'profile'
      end
      collection do 
        patch 'update_password'
      end
      resources :addresses
    end
    
    resources :contacts do
      collection do
        get 'search'
      end
      resources :addresses
    end
    resources :fund_transfers
    
  end
  root to: 'admins#index'
  
  
  resources :admins, only: [:index]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ams</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg">
    <!-- container section start -->
    <section id="container" class="">
      <!--header start-->
      <header class="header dark-bg">
        <div class="toggle-nav">
          <div class="icon-reorder tooltips" data-original-title="Toggle Navigation" data-placement="bottom"><i class="icon_menu"></i></div>
        </div>

        <!--logo start-->
        <a href="index.html" class="logo">AMS <span class="lite">Admin</span></a>
        <!--logo end-->

        <div class="nav search-row" id="top_menu">
          <!--  search form start -->
          <ul class="nav top-menu">                    
            <li>
              <form class="navbar-form">
                <input class="form-control" placeholder="Search" type="text">
              </form>
            </li>                    
          </ul>
          <!--  search form end -->                
        </div>

        <div class="top-nav notification-row">                
          <!-- notificatoin dropdown start-->
          <ul class="nav pull-right top-menu">
            <!-- user login dropdown start-->
            <li class="dropdown">
              <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                <span class="profile-ava">
                  <img alt="" src="/assets/avatar1_small.jpg">
                </span>
                <span class="username"><%= current_user.email%></span>
                <b class="caret"></b>
              </a>
              <ul class="dropdown-menu extended logout">
                <div class="log-arrow-up"></div>
                <li class="eborder-top">
                  <a href="<%= profile_user_path(current_user) %>"><i class="icon_profile"></i> My Profile</a>
                </li>                
                <li>
                  <a href="<%= edit_user_path(current_user) %>"><i class="icon_key_alt"></i> Update Password</a>
                </li>
                <li>
                  <a href="#"><i class="icon_clock_alt"></i> Timeline</a>
                </li>
                <li>
                  <a href="#"><i class="icon_chat_alt"></i> Chats</a>
                </li>
                <li>
                  <a href="<%= destroy_user_session_path %>" data-method="DELETE" data-confirm="Are you sure?"><i class="icon_key_alt"></i> Log Out</a>
                </li>
                <li>
                  <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                </li>
                <li>
                  <a href="documentation.html"><i class="icon_key_alt"></i> Documentation</a>
                </li>
              </ul>
            </li>
            <!-- user login dropdown end -->
          </ul>
          <!-- notificatoin dropdown end-->
        </div>
      </header> 
      <!--header end-->


      <!--sidebar start-->
      <aside>
        <div id="sidebar"  class="nav-collapse ">
          <!-- sidebar menu start-->
          <ul class="sidebar-menu">                
            <li class="<%= @admin_active %>">
              <a class="" href="<%= root_path %>">
                <i class="icon_house_alt"></i>
                <span>Dashboard</span>
              </a>
            </li>
            <li class="sub-menu <%= @contact_active %>">
              <a href="<%= contacts_path %>" class="">
                <i class="icon_document_alt"></i>
                <span>Contacts</span>                
              </a>
            </li>   

            <li class="sub-menu <%= @fund_active %>">
              <a href="<%= fund_transfers_path %>" class="">
                <i class="icon_wallet_alt"></i>
                <span>Fund Transfer</span>                
              </a>
            </li> 


            <li class="sub-menu ">
              <a href="javascript:;" class="">
                <i class="icon_desktop"></i>
                <span>UI Fitures</span>
                <span class="menu-arrow arrow_carrot-right"></span>
              </a>
              <ul class="sub">
                <li><a class="" href="general.html">Elements</a></li>
                <li><a class="" href="buttons.html">Buttons</a></li>
                <li><a class="" href="grids.html">Grids</a></li>
              </ul>
            </li>
            <li>
              <a class="" href="widgets.html">
                <i class="icon_genius"></i>
                <span>Widgets</span>
              </a>
            </li>
            <li>                     
              <a class="" href="chart-chartjs.html">
                <i class="icon_piechart"></i>
                <span>Charts</span>

              </a>

            </li>

            <li class="sub-menu">
              <a href="javascript:;" class="">
                <i class="icon_table"></i>
                <span>Tables</span>
                <span class="menu-arrow arrow_carrot-right"></span>
              </a>
              <ul class="sub">
                <li><a class="" href="basic_table.html">Basic Table</a></li>
              </ul>
            </li>

            <li class="sub-menu">
              <a href="javascript:;" class="">
                <i class="icon_documents_alt"></i>
                <span>Pages</span>
                <span class="menu-arrow arrow_carrot-right"></span>
              </a>
              <ul class="sub">                          
                <li><a class="" href="profile.html">Profile</a></li>
                <li><a class="" href="login.html"><span>Login Page</span></a></li>
                <li><a class="" href="blank.html">Blank Page</a></li>
                <li><a class="" href="404.html">404 Error</a></li>
              </ul>
            </li>

          </ul>
          <!-- sidebar menu end-->
        </div>
      </aside>
      <!--sidebar end-->




      <section id="main-content">
        <section class="wrapper">
          <div class="row">
            <div class="col-lg-12">    
              <%= render 'layouts/messages' %>    
            </div>
          </div>
          <%= yield %>
        </section>
        <div class="text-right">
          <div class="credits">
            <!-- 
                All the links in the footer should remain intact. 
                You can delete the links only if you purchased the pro version.
                Licensing information: https://bootstrapmade.com/license/
                Purchase the pro version form: https://bootstrapmade.com/buy/?theme=NiceAdmin
            -->
            <a href="javascript:void(0);">Powered</a> by <a href="javascript:void(0);">Jhantoo Kumar Shaw</a>
          </div>
        </div>
      </section>
    </section>
    <!-- container section end -->
  </body>
  <script>
    function goBack() {
      window.history.back();
    }
  </script>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Creative - Bootstrap 3 Responsive Admin Template">
    <meta name="author" content="GeeksLabs">
    <meta name="keyword" content="Creative, Dashboard, Admin, Template, Theme, Bootstrap, Responsive, Retina, Minimal">
    <link rel="shortcut icon" href="/assets/favicon.ico">

    <title>Ams</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="login-img3-body bg">
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>

      <div class="text-right">
        <div class="credits">
          <!-- 
              All the links in the footer should remain intact. 
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version form: https://bootstrapmade.com/buy/?theme=NiceAdmin
          -->
          <a href="javascript:void(0);">Powered</a> by <a href="javascript:void(0);">Jhantoo Kumar Shaw</a>
        </div>
      </div>

    </div>
    <!-- container section end -->
  </body>
</html>